# This environment requires Linux
# macOS and Windows are not supported

name: spacedeconv-env

channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
  - nodefaults

dependencies:
  - r-base = 4.3.3
  - r-essentials
  - python = 3.10
  - compilers
  - r-devtools

  # conda-forge R packages
  - r-pak
  - r-anndata
  - r-sf
  - r-ggpubr
  - r-spatstat.geom
  - r-spatstat.explore
  - r-progress
  - r-circlize
  - r-patchwork
  - r-reticulate >= 1.25
  - r-corrplot
  - r-ggridges
  - r-testit
  - r-multimode
  - r-psych
  - r-immunedeconv
  - r-seurat = 4.4.0
  - r-cli
  - r-pkgdown
  - r-rmarkdown
  - r-uuid
  - r-knitr
  - r-testthat
  - r-tidyr
  - r-xcell
  - r-markdown
  - r-epic
  - r-seuratobject
  - r-plotly
  - r-pbapply
  - r-terra >= 1.5-12
  - r-magick
  - r-igraph >= 1.2.4.1
  - r-rcpp >= 1.0.7
  - r-rcpparmadillo
  - r-mcmcpack
  - r-fields
  - r-concaveman
  - r-sp
  - r-dplyr
  - r-rann
  - r-ggplot2 >= 3.1.1
  - r-reshape2
  - r-rcolorbrewer
  - r-scatterpie
  - r-ggcorrplot
  - r-nnls
  - r-pbmcapply
  - r-rcppml
  - r-nmf
  - r-spatstat.random
  - r-gtools
  - r-checkmate
  - r-cowplot >= 0.9.4
  - r-data.table >= 1.12.2
  - r-dbscan >= 1.1-3
  - r-deldir >= 1.0.6
  - r-future.apply
  - r-ggrepel
  - r-jsonlite
  - r-magrittr
  - r-matrixstats >= 0.55.0
  - r-progressr
  - r-rtsne
  - r-scales >= 1.0.0
  - r-uwot

  # Bioconductor R packages
  - bioconductor-singlecellexperiment
  - bioconductor-spatialexperiment
  - bioconductor-summarizedexperiment
  - bioconductor-edger
  - bioconductor-s4vectors
  - bioconductor-delayedarray
  - bioconductor-decoupler
  - bioconductor-complexheatmap
  - bioconductor-omnipathr # currently not available for R 4.4 at bioconda
  - bioconductor-dropletutils
  - bioconductor-spotlight
  - bioconductor-scuttle
  - bioconductor-orthology.eg.db
  - bioconductor-org.mm.eg.db
  - bioconductor-org.hs.eg.db
  - bioconductor-annotationdbi
  - bioconductor-biocsingular
  - bioconductor-matrixgenerics
  - bioconductor-sparsematrixstats
  - bioconductor-limma
  - bioconductor-scran
  - bioconductor-zellkonverter
  - r-spacexr

  # Python packages
  - python-igraph
  - leidenalg
  - python-louvain
  - scikit-learn
  - scanpy

  # cell2location packages
  - pytest >= 6.2.2
  - numpy >= 1.18.5
  - pandas >= 1.0.4
  - jupyter >= 1.0.0
  - ipykernel >= 5.3.4
  - leidenalg >= 0.8.0
  - python-igraph >= 0.8.2
  - nose >= 1.3.7
  - scanpy >= 1.5.1
  - scipy >= 1.4.1
  - louvain >= 0.6.1
  - hyperopt >= 0.2.4
  - loompy >= 2.0.16
  - cmake >= 3.17.0
  - dill >= 0.3.1
  - ipython >= 7.15.0
  - bbknn >= 1.3.9
  - seaborn >= 0.10.1
  - matplotlib >= 3.2.1
  - request >= 2.83.1
  - cython >= 0.29.17

  - scvi-tools = 0.20.3
  - pytorch = 2.2.2
  - pytorch-cuda = 11.8
  - pyro-ppl = 1.9.1
  - anndata = 0.9.2
  - numpy = 1.24.3

  - pip
  - setuptools = 80.10.2
  - pip:
      - cell2location==0.1.3
      - anndata==0.9.2
      - numpy==1.24.3
      - rectanglepy @ git+https://github.com/ComputationalBiomedicineGroup/Rectangle.git@v1.4.2
