---
title: "Quality control"
output: html_document
---

<style type="text/css">
   .main-container {max-width: 100%;}
   .row {display: flex;}
   .column {flex: 50%;}
</style>

```{r, echo=FALSE}
# Pepare packages
library(SpatialExperiment)
library(spacedeconv)
library(scuttle)
library(ggplot2)
```


```{r, echo=FALSE}
# Add QC metrics
library(scuttle)
spe <- scuttle::addPerCellQC(spe)
```

```{r, echo = FALSE, results='asis'}

# number of total spots
ntotal_spots <- ncol(counts(spe))

# total number of genes
ntotal_genes <- dim(spe)[1]

# Range of total UMIs per spot
range_umiperspot <- range(colData(spe)$sum)

# % UMIs >= 500
UMI_above500 <- sum(colData(spe)$sum >= 500) / dim(spe)[1]

# % UMIs < 500
UMI_below500 <- sum(colData(spe)$sum < 500) / dim(spe)[1]

# Range of detected genes per spot
range_genesperspot <- range(colSums(counts(spe) > 0))
```


<div class = "row">
<div class = "column">
# Plot UMI and number of detected genes - log transformed
```{r, echo=FALSE, fig.align='left'}
# Plot UMI
plot_umi_count(spe, offset_rotation = T, transform_scale = "log")

# Plot number of detected genes
plot_ndetected_genes(spe, offset_rotation = T, transform_scale = "log")
```
</div>

<div class = "column">
# QC metrics
```{r, echo = FALSE}
# Make a table
res <- c(ntotal_genes = ntotal_genes, ntotal_spots = ntotal_spots, range_umiperspot = paste0(range_umiperspot[1], "-",range_umiperspot[2]), UMI_above500 = UMI_above500, UMI_below500 = UMI_below500, range_genesperspot = paste0(range_genesperspot[1], "-", range_genesperspot[2]))

library(knitr)
kable(res)
```


</div>
</div>
