# The purpose of this action is to generate the website using pkgdown.
# On a commit to the main branch, the website will be deployed on github pages.
# In pull requests, a zip file with the website will be generated which can be downloaded
# in order to preview the website.
#
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-22.04
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Update system dependencies
        # due to recent versions of GLIBC missing
        run: |
          sudo apt-get update && sudo apt-get install cmake libstdc++6 \
          libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev \
          libharfbuzz-dev libfribidi-dev \
          libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev -y

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"' # do not install suggests
          extra-packages: any::pkgdown, local::. #, omnideconv/immunedeconv, satijalab/seurat
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: docs

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
        with:
          publish-dir: "./docs"
          github-token: ${{ secrets.TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
